filebeat.inputs:
- type: filestream
  id: cdmx-colonias
  paths:
   - ./data/*.geojson

output.elasticsearch:
  index: "cdmx-colonias-%{+YYYY.MM.dd}"
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"

setup.template.name: "cdmx-colonias"
setup.template.pattern: "cdmx-colonias-"