version: "3.8"

services:
  filebeat-cdmx-seguridad:
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    user: root
    volumes:
      - ${CERT_PATH}:/usr/share/filebeat/certs
      - filebeatdata-cdmx-seguridad:/usr/share/filebeat/data
      - "./filebeat/cdmx-seguridad.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "./data/cdmx-seguridad:/usr/share/filebeat/data/:ro"
  filebeat-cdmx-colonias:
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    user: root
    volumes:
      - ${CERT_PATH}:/usr/share/filebeat/certs
      - filebeatdata-cdmx-colonias:/usr/share/filebeat/data
      - "./filebeat/cdmx-colonias.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "./data/cdmx-colonias:/usr/share/filebeat/data/:ro"
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
      - KIBANA_HOSTS=http://kibana:5601
  downloader:
    build: .
    volumes:
      - ./data:/data

volumes:
  filebeatdata-cdmx-seguridad:
    driver: local
  filebeatdata-cdmx-colonias:
    driver: local

networks:
  default:
    name: elastic
    external: false